services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc-mw-if
    depends_on:
      - php
    ports:
      - "28082:80"
    environment:
      - VITE_API_URL=https://cc.multiweb.id
      - VITE_API_CURRENCY_URL=https://api-currency.baliweddingvilla.com
      - VITE_API_CURRENCY_API_KEY=5c3c28eb9ffed1087400d2f4274731a2
      - VITE_GOOGLE_MAP_KEY=AIzaSyD8z5-LNZRvlzFDBPLM-sh763_SCxtrhH0
    # Optional dev volumes (uncomment for live edits; baked-in otherwise)
    # volumes:
    #   - ./property:/usr/local/apache2/htdocs/property

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./property:/usr/local/apache2/htdocs/property # NEW: Mount for FPM to access index.php
    # Optional dev volume (already covered above)
